GET http://localhost:3001/api/contacts

###
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
    "FullName": "payal",
    "Email": "payal@gmail.com",
    "PhoneNumber": "4585965456",
    "Address": "suomi"
}

###
DELETE http://localhost:3001/api/contacts/aoi4i88vf
