GET http://localhost:3001/api/contacts

###
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
    "FullName": "payal",
    "Email": "payal@mail.com",
    "PhoneNumber": 45859654561233,
    "Address": "suomi"
}

###
PUT http://localhost:3001/api/contacts/66b686c55f0267564c0d0dad
Content-Type: application/json

{
    "FullName": "updated name",
    "Email": "updated@mail.com",
    "PhoneNumber": 1234567890,
    "Address": "updated address"
}


###
DELETE http://localhost:3001/api/contacts/aoi4i88vf
